using AutoMapper;
using InterviewTest.Application.Services.Employees.Base.Models;
using InterviewTest.Application.Services.Tasks.Base.Models;

namespace InterviewTest.AutoMapperRules.Profiles
{
    //public class AutoMapperGlobalProfile : AutoMapper.Profile
    //{
    //    public AutoMapperGlobalProfile()
    //    {
    //        BaseEmployeeeDTO.CreateMappingRules(this);
    //        BaseTaskDTO.CreateMappingRules(this);
    //        CreateMap<BaseTaskDTO, Task>()
    //            .ForMember(dest => dest.Id, opt => opt.Ignore()) // Assuming the ID is autogenerated by the database
    //            .ReverseMap();
    //    }

    //}

    public class AutoMapperGlobalProfile : Profile
    {
        public AutoMapperGlobalProfile()
        {
            BaseEmployeeeDTO.CreateMappingRules(this);
            BaseTaskDTO.CreateMappingRules(this);

        }

    }
}
